#!/bin/sh
mkdir -p /var/lib/slqm

# Allow access to SLQM web UI from LAN
uci -q delete firewall.slqm_web 2>/dev/null
uci set firewall.slqm_web=rule
uci set firewall.slqm_web.name='Allow-SLQM-WebUI'
uci set firewall.slqm_web.src='lan'
uci set firewall.slqm_web.dest_port='8275'
uci set firewall.slqm_web.proto='tcp'
uci set firewall.slqm_web.target='ACCEPT'
uci commit firewall
/etc/init.d/firewall reload 2>/dev/null

/etc/init.d/slqm enable
/etc/init.d/slqm start
exit 0
